MYINT = ['IntegerField', 'NumberInput']
MYDEC = ['DecimalField', 'NumberInput']
MYTXT = ['CharField', 'TextInput']
# for these we need, the pandas dfs to smartly select the choices, put them in a tuple or list
MYTXT_CH = ['CharField', 'Select']
MYFOREIGN = ['ForeignKey', 'Select']

# from all_choices import ALL_MY_CHOICES_GENERAL
varhiers_dic = {}

vars_dic = {'agricultural_population': {'db_name': 'general', 'main_desc': 'No Explanations.', 'main_desc_source': '', 'notes': 'Notes for the Variable agricultural_population are missing!', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'Productivity', 'needsSeshatCommon': None, 'col1': {'colname': 'agricultural_population', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'agricultural_population', 'units': 'People', 'scale': 1000}}, 'arable_land': {'db_name': 'general', 'main_desc': 'No Explanations.', 'main_desc_source': '', 'notes': 'Notes for the Variable arable_land are missing!', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'Productivity', 'needsSeshatCommon': None, 'col1': {'colname': 'arable_land', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'arable_land', 'units': 'mu?', 'scale': 1000}}, 'arable_land_per_farmer': {'db_name': 'general', 'main_desc': 'No Explanations.', 'main_desc_source': '', 'notes': 'Notes for the Variable arable_land_per_farmer are missing!', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'Productivity', 'needsSeshatCommon': True, 'col1': {'colname': 'arable_land_per_farmer', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'arable_land_per_farmer', 'units': 'mu?', 'scale': 1}}, 'gross_grain_shared_per_agricultural_population': {'db_name': 'general', 'main_desc': 'No Explanations.', 'main_desc_source': '', 'notes': 'Notes for the Variable gross_grain_shared_per_agricultural_population are missing!', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'Productivity', 'needsSeshatCommon': None, 'col1': {'colname': 'gross_grain_shared_per_agricultural_population', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'gross_grain_shared_per_agricultural_population', 'units': '(catties per capita)', 'scale': 1}}, 'net_grain_shared_per_agricultural_population': {'db_name': 'general', 'main_desc': 'No Explanations.', 'main_desc_source': '', 'notes': 'Notes for the Variable net_grain_shared_per_agricultural_population are missing!', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'Productivity', 'needsSeshatCommon': None, 'col1': {'colname': 'net_grain_shared_per_agricultural_population', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'net_grain_shared_per_agricultural_population', 'units': '(catties per capita)', 'scale': 1}}, 'surplus': {'db_name': 'general', 'main_desc': 'No Explanations.', 'main_desc_source': '', 'notes': 'Notes for the Variable surplus are missing!', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'Productivity', 'needsSeshatCommon': True, 'col1': {'colname': 'surplus', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'surplus', 'units': '(catties per capita)', 'scale': 1}}, 'military_expense': {'db_name': 'general', 'main_desc': 'Main Descriptions for the Variable military_expense are missing!', 'main_desc_source': 'https://en.wikipedia.org/wiki/Disease_outbreak', 'notes': 'Not sure about Section and Subsection.', 'cols': 2, 'section': 'Economy Variables', 'subsection': 'State Finances', 'needsSeshatCommon': None, 'col1': {'colname': 'conflict', 'dtype': ['CharField', 'TextInput'], 'varname': 'military_expense'}, 'col2': {'colname': 'expenditure', 'dtype': ['DecimalField', 'NumberInput'], 'varname': 'military_expense', 'units': 'millions silver taels', 'scale': 1, 'decimal_places': 15, 'max_digits': 20}}, 'silver_inflow': {'db_name': 'general', 'main_desc': 'Silver inflow in Millions of silver taels??', 'main_desc_source': '', 'notes': 'Needs suoervision on the units and scale.', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'State Finances', 'needsSeshatCommon': None, 'col1': {'colname': 'silver_inflow', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'silver_inflow', 'units': 'Millions of silver taels??', 'scale': 1000000}}, 'silver_stock': {'db_name': 'general', 'main_desc': 'Silver stock in Millions of silver taels??', 'main_desc_source': '', 'notes': 'Needs suoervision on the units and scale.', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'State Finances', 'needsSeshatCommon': None, 'col1': {'colname': 'silver_stock', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'silver_stock', 'units': 'Millions of silver taels??', 'scale': 1000000}}, 'total_population': {'db_name': 'general', 'main_desc': 'Total population or simply population, of a given area is the total number of people in that area at a given time.', 'main_desc_source': '', 'notes': 'Note that the population values are scaled.', 'cols': 1, 'section': 'Social Complexity Variables', 'subsection': 'Social Scale', 'needsSeshatCommon': None, 'col1': {'colname': 'total_population', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'total_population', 'units': 'People', 'scale': 1000}}, 'gdp_per_capita': {'db_name': 'general', 'main_desc': "The Gross Domestic Product per capita, or GDP per capita, is a measure of a country's economic output that accounts for its number of people. It divides the country's gross domestic product by its total population.", 'main_desc_source': 'https://www.thebalance.com/gdp-per-capita-formula-u-s-compared-to-highest-and-lowest-3305848', 'notes': 'The exact year based on which the value of Dollar is taken into account is not clear.', 'cols': 1, 'section': 'Economy Variables', 'subsection': 'Productivity', 'needsSeshatCommon': None, 'col1': {'colname': 'gdp_per_capita', 'dtype': ['DecimalField', 'NumberInput'], 'varname': 'gdp_per_capita', 'units': 'Dollars (in 2009?)', 'scale': 1, 'decimal_places': 15, 'max_digits': 20}}, 'drought_events': {'db_name': 'general', 'main_desc': 'number of geographic sites indicating drought', 'main_desc_source': 'https://www1.ncdc.noaa.gov/pub/data/paleo/historical/asia/china/reaches2020drought-category-sites.txt', 'notes': 'Notes for the Variable drought_events are missing!', 'cols': 1, 'section': 'Well Being', 'subsection': 'Biological Well-Being', 'needsSeshatCommon': None, 'col1': {'colname': 'drought_events', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'drought_events', 'units': 'Numbers', 'scale': 1}}, 'locust_events': {'db_name': 'general', 'main_desc': 'number of geographic sites indicating locusts', 'main_desc_source': 'https://www1.ncdc.noaa.gov/pub/data/paleo/historical/asia/china/reaches2020drought-category-sites.txt', 'notes': 'Notes for the Variable locust_events are missing!', 'cols': 1, 'section': 'Well Being', 'subsection': 'Biological Well-Being', 'needsSeshatCommon': None, 'col1': {'colname': 'locust_events', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'locust_events', 'units': 'Numbers', 'scale': 1}}, 'socioeconomic_turmoil_events': {'db_name': 'general', 'main_desc': 'number of geographic sites indicating socioeconomic turmoil', 'main_desc_source': 'https://www1.ncdc.noaa.gov/pub/data/paleo/historical/asia/china/reaches2020drought-category-sites.txt', 'notes': 'Notes for the Variable socioeconomic_turmoil_events are missing!', 'cols': 1, 'section': 'Well Being', 'subsection': 'Biological Well-Being', 'needsSeshatCommon': None, 'col1': {'colname': 'socioeconomic_turmoil_events', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'socioeconomic_turmoil_events', 'units': 'Numbers', 'scale': 1}}, 'crop_failure_events': {'db_name': 'general', 'main_desc': 'number of geographic sites indicating crop failure', 'main_desc_source': 'https://www1.ncdc.noaa.gov/pub/data/paleo/historical/asia/china/reaches2020drought-category-sites.txt', 'notes': 'Notes for the Variable crop_failure_events are missing!', 'cols': 1, 'section': 'Well Being', 'subsection': 'Biological Well-Being', 'needsSeshatCommon': None, 'col1': {'colname': 'crop_failure_events', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'crop_failure_events', 'units': 'Numbers', 'scale': 1}}, 'famine_events': {'db_name': 'general', 'main_desc': 'number of geographic sites indicating famine', 'main_desc_source': 'https://www1.ncdc.noaa.gov/pub/data/paleo/historical/asia/china/reaches2020drought-category-sites.txt', 'notes': 'Notes for the Variable famine_events are missing!', 'cols': 1, 'section': 'Well Being', 'subsection': 'Biological Well-Being', 'needsSeshatCommon': None, 'col1': {'colname': 'famine_events', 'dtype': ['IntegerField', 'NumberInput'], 'varname': 'famine_events', 'units': 'Numbers', 'scale': 1}}, 'disease_outbreak': {'db_name': 'general', 'main_desc': 'A sudden increase in occurrences of a disease when cases are in excess of normal expectancy for the location or season.', 'main_desc_source': 'https://en.wikipedia.org/wiki/Disease_outbreak', 'notes': 'Notes for the Variable disease_outbreak are missing!', 'cols': 6, 'section': 'Well Being', 'subsection': 'Biological Well-Being', 'needsSeshatCommon': None, 'col1': {'colname': 'longitude', 'dtype': ['DecimalField', 'NumberInput'], 'varname': 'disease_outbreak', 'units': 'Degrees', 'min': -180, 'max': 180, 'scale': 1, 'decimal_places': 15, 'max_digits': 20}, 'col2': {'colname': 'latitude', 'dtype': ['DecimalField', 'NumberInput'], 'varname': 'disease_outbreak', 'units': 'Degrees', 'min': -180, 'max': 180, 'scale': 1, 'decimal_places': 15, 'max_digits': 20}, 'col3': {'colname': 'elevation', 'dtype': ['DecimalField', 'NumberInput'], 'varname': 'disease_outbreak', 'units': 'Meters', 'max': 5000, 'scale': 1, 'decimal_places': 15, 'max_digits': 20}, 'col4': {'colname': 'sub_category', 'dtype': ['CharField', 'Select'], 'varname': 'disease_outbreak', 'choices': ['Peculiar Epidemics', 'Pestilence', 'Miasm', 'Pox', 'Uncertain Pestilence', 'Dysentery', 'Malaria', 'Influenza', 'Cholera', 'Diptheria', 'Plague']}, 'col5': {'colname': 'magnitude', 'dtype': ['CharField', 'Select'], 'varname': 'disease_outbreak', 'choices': ['Uncertain', 'Light', 'Heavy', 'No description', 'Heavy- Multiple Times', 'No Happening', 'Moderate']}, 'col6': {'colname': 'duration', 'dtype': ['CharField', 'Select'], 'varname': 'disease_outbreak', 'choices': ['No description', 'Over 90 Days', 'Uncertain', '30-60 Days', '1-10 Days', '60-90 Days']}}}

general_vars_dic_new = {'polity_research_assistant': {'varname': 'polity_research_assistant',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The RA(s) who worked on a polity.',
  'section': 'General Variables',
  'subsection': 'Staff',
  'col1': {'colname': 'polity_ra',
   'dtype': ['ForeignKey', 'Select'],
   'varname': 'polity_research_assistant',
   'col_exp': 'The RA of a polity.',
   'foreign_key': 'Seshat_Expert',
   'foreign_key_related_name': 'seshat_research_assistant'}},
 'polity_utm_zone': {'varname': 'polity_utm_zone',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The UTM Zone of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'utm_zone',
   'dtype': ['CharField', 'TextInput'],
   'varname': 'polity_utm_zone',
   'col_exp': 'The details of UTM_ZONE.',
   'max_digits': 5,
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}},
 'polity_original_name': {'varname': 'polity_original_name',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The original name of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'original_name',
   'dtype': ['CharField', 'TextInput'],
   'varname': 'polity_original_name',
   'col_exp': 'The details of original_name.',
   'max_digits': 100,
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}},
 'polity_alternative_name': {'varname': 'polity_alternative_name',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The alternative name of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'alternative_name',
   'dtype': ['CharField', 'TextInput'],
   'varname': 'polity_alternative_name',
   'col_exp': 'The details of alternative_name.',
   'max_digits': 100,
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}},
 'polity_peak_years': {'varname': 'polity_peak_years',
  'cols': 2,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The peak years of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'peak_year_from',
   'dtype': ['IntegerField', 'NumberInput'],
   'varname': 'polity_peak_years',
   'col_exp': 'The beginning of the peak years for a polity.',
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'},
  'col2': {'colname': 'peak_year_to',
   'dtype': ['IntegerField', 'NumberInput'],
   'varname': 'polity_peak_years',
   'col_exp': 'The end of the peak years for a polity.',
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}},
 'polity_duration': {'varname': 'polity_duration',
  'cols': 2,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The lifetime of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'polity_year_from',
   'dtype': ['IntegerField', 'NumberInput'],
   'varname': 'polity_duration',
   'col_exp': 'The beginning year for a polity.',
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'},
  'col2': {'colname': 'polity_year_to',
   'dtype': ['IntegerField', 'NumberInput'],
   'varname': 'polity_duration',
   'col_exp': 'The end year for a polity.',
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}},
 'polity_degree_of_centralization': {'varname': 'polity_degree_of_centralization',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The degree of centralization of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'degree_of_centralization',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_degree_of_centralization',
   'col_exp': 'The details of degree_of_centralization.',
   'max_digits': 50,
   'choices': 'DEGREE_OF_CENTRALIZATION_CHOICES',
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}},
 'polity_suprapolity_relations': {'varname': 'polity_suprapolity_relations',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The supra polity relations of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'supra_polity_relations',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_suprapolity_relations',
   'col_exp': 'The details of supra polity relations.',
   'max_digits': 50,
   'choices': 'SUPRA_POLITY_RELATIONS_CHOICES',
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}},
 'polity_capital': {'varname': 'polity_capital',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The capital of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'capital',
   'dtype': ['CharField', 'TextInput'],
   'varname': 'polity_capital',
   'col_exp': 'The capital of a polity.',
   'max_digits': 70,
   'null_meaning': 'This polity did not have a capital.'}},
 'polity_language': {'varname': 'polity_language',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The language of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'language',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_language',
   'col_exp': 'The language of a polity.',
   'max_digits': 70,
   'choices': 'LANGUAGE_CHOICES',
   'null_meaning': 'This polity did not have a language.'}},
 'polity_linguistic_family': {'varname': 'polity_linguistic_family',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The linguistic family of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'linguistic_family',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_linguistic_family',
   'col_exp': 'The linguistic family of a polity.',
   'max_digits': 70,
   'choices': 'LINGUISTIC_FAMILY_CHOICES',
   'null_meaning': 'This polity did not have a linguistic family.'}},
 'polity_language_genus': {'varname': 'polity_language_genus',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The language genus of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'language_genus',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_language_genus',
   'col_exp': 'The language genus of a polity.',
   'max_digits': 70,
   'choices': 'LINGUISTIC_FAMILY_CHOICES',
   'null_meaning': 'This polity did not have a language Genus.'}},
 'polity_religion_genus': {'varname': 'polity_religion_genus',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The religion genus of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'religion_genus',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_religion_genus',
   'col_exp': 'The religion genus of a polity.',
   'max_digits': 70,
   'choices': 'RELIGION_GENUS_CHOICES',
   'null_meaning': 'This polity did not have a religion genus.'}},
 'polity_religion_family': {'varname': 'polity_religion_family',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The religion family of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'religion_family',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_religion_family',
   'col_exp': 'The religion family of a polity.',
   'max_digits': 70,
   'choices': 'RELIGION_FAMILY_CHOICES',
   'null_meaning': 'This polity did not have a religion family.'}},
 'polity_religion': {'varname': 'polity_religion',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The religion of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'religion',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_religion',
   'col_exp': 'The religion of a polity.',
   'max_digits': 70,
   'choices': 'RELIGION_CHOICES',
   'null_meaning': 'This polity did not have a religion.'}},
 'polity_relationship_to_preceding_entity': {'varname': 'polity_relationship_to_preceding_entity',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The polity relationship to preceding (quasi)polity',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'relationship_to_preceding_entity',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_relationship_to_preceding_entity',
   'col_exp': 'The polity relationship to preceding (quasi)polity',
   'max_digits': 70,
   'choices': 'RELATIONSHIP_TO_PRECEDING_ENTITY_CHOICES',
   'null_meaning': 'This polity did not have a relationship to preceding (quasi)polity'}},
 'polity_preceding_entity': {'varname': 'polity_preceding_entity',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The preceding entity of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'preceding_entity',
   'dtype': ['CharField', 'TextInput'],
   'varname': 'polity_preceding_entity',
   'col_exp': 'The preceding entity (or the largest settlement) of a polity.',
   'max_digits': 70,
   'null_meaning': 'This polity did not have a preceding entity.'}},
 'polity_succeeding_entity': {'varname': 'polity_succeeding_entity',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The succeeding entity of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'succeeding_entity',
   'dtype': ['CharField', 'TextInput'],
   'varname': 'polity_succeeding_entity',
   'col_exp': 'The succeeding entity (or the largest settlement) of a polity.',
   'max_digits': 70,
   'null_meaning': 'This polity did not have a succeeding entity.'}},
 'polity_supracultural_entity': {'varname': 'polity_supracultural_entity',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The supracultural entity of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'supracultural_entity',
   'dtype': ['CharField', 'TextInput'],
   'varname': 'polity_supracultural_entity',
   'col_exp': 'The supracultural entity (or the largest settlement) of a polity.',
   'max_digits': 100,
   'null_meaning': 'This polity did not have a supracultural entity.'}},
 'polity_scale_of_supracultural_interaction': {'varname': 'polity_scale_of_supracultural_interaction',
  'cols': 2,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The scale_of_supra_cultural_interaction of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'scale_from',
   'dtype': ['IntegerField', 'NumberInput'],
   'varname': 'polity_scale_of_supracultural_interaction',
   'col_exp': 'The lower scale of supra cultural interactionfor a polity.',
   'units': 'km squared',
   'min': 0,
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'},
  'col2': {'colname': 'scale_to',
   'dtype': ['IntegerField', 'NumberInput'],
   'varname': 'polity_scale_of_supracultural_interaction',
   'col_exp': 'The upper scale of supra cultural interactionfor a polity.',
   'units': 'km squared',
   'min': 0,
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}},
 'polity_alternate_religion_genus': {'varname': 'polity_alternate_religion_genus',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The alternate religion genus of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'alternate_religion_genus',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_alternate_religion_genus',
   'col_exp': 'The alternate religion genus of a polity.',
   'max_digits': 70,
   'choices': 'RELIGION_GENUS_CHOICES',
   'null_meaning': 'This polity did not have a alternatereligion genus.'}},
 'polity_alternate_religion_family': {'varname': 'polity_alternate_religion_family',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The alternate religion family of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'alternate_religion_family',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_alternate_religion_family',
   'col_exp': 'The alternate religion family of a polity.',
   'max_digits': 70,
   'choices': 'RELIGION_FAMILY_CHOICES',
   'null_meaning': 'This polity did not have a alternate religion family.'}},
 'polity_alternate_religion': {'varname': 'polity_alternate_religion',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The alternate religion  of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'alternate_religion',
   'dtype': ['CharField', 'Select'],
   'varname': 'polity_alternate_religion',
   'col_exp': 'The alternate religion of a polity.',
   'max_digits': 70,
   'choices': 'RELIGION_CHOICES',
   'null_meaning': 'This polity did not have a alternate religion .'}},
 'polity_expert': {'varname': 'polity_expert',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The expert of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'expert',
   'dtype': ['ForeignKey', 'Select'],
   'varname': 'polity_expert',
   'col_exp': 'The expert of a polity.',
   'foreign_key': 'Seshat_Expert',
   'foreign_key_related_name': 'seshat_expert',
   'null_meaning': 'This polity did not have an expert.'}},
 'polity_editor': {'varname': 'polity_editor',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The editor of a polity.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'editor',
   'dtype': ['ForeignKey', 'Select'],
   'varname': 'polity_editor',
   'col_exp': 'The editor of a polity.',
   'foreign_key': 'Seshat_Expert',
   'foreign_key_related_name': 'seshat_editor',
   'null_meaning': 'This polity did not have an editor.'}},
 'polity_religious_tradition': {'varname': 'polity_religious_tradition',
  'cols': 1,
  'needsSeshatCommon': True,
  'db_name': 'general',
  'main_desc': 'The details of religious traditions.',
  'section': 'General Variables',
  'subsection': 'General',
  'col1': {'colname': 'religious_tradition',
   'dtype': ['CharField', 'TextInput'],
   'varname': 'polity_religious_tradition',
   'col_exp': 'The details of religious traditions.',
   'max_digits': 100,
   'null_meaning': 'No_Value_Provided_in_Old_Wiki'}}}